import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { Toaster as Sonner } from "sonner";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import Navbar from "@/features/public/components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const font = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <NuqsAdapter>
        <body className={`${font.className} antialiased`}>
          <Navbar />
          {children}
          <Toaster />
          <Sonner />
        </body>
      </NuqsAdapter>
    </html>
  );
}
